"""create users table

Revision ID: f3de6c7d7bf1
Revises:
Create Date: 2026-10-04 18:40:50.478438+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3de6c7d7bf1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("customer", "helper", "admin", name="user_role_enum"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_id_verified", sa.Boolean(), nullable=False),
        sa.Column("profile_photo_url", sa.String(length=500), nullable=True),
        sa.Column("trust_score", sa.Double(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_table("users")
    # drop_table does not remove the enum type created implicitly by the
    # sa.Enum(...) above, which leaves an orphan behind and makes the next
    # upgrade fail with DuplicateObjectError: type "user_role_enum" already
    # exists. Drop it explicitly. checkfirst makes this idempotent, so it is
    # safe on environments where the type is already absent.
    sa.Enum(name="user_role_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
